# Generated by Django 6.0.3 on 2026-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('level', models.CharField(choices=[('A1', 'A1 — Beginner'), ('A2', 'A2 — Elementary'), ('B1', 'B1 — Intermediate'), ('B2', 'B2 — Upper Intermediate'), ('C1', 'C1 — Advanced'), ('C2', 'C2 — Proficiency')], max_length=2, verbose_name='Уровень')),
                ('duration_months', models.PositiveIntegerField(default=3, verbose_name='Длительность')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена (руб)')),
            ],
        ),
    ]
